version: "3.5"
services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      my-network:
        aliases:
            - nginx
    depends_on:
      - flask
  postgres:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: "killer-database"
      POSTGRES_USER: "killer-admin"
      POSTGRES_PASSWORD: "secretkey"
    ports:
      - "5432:5432"
    networks:
      my-network:
        aliases:
          - postgres
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    networks:
      my-network:
        aliases:
            - flask-app
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    command: python main.py
    depends_on:
      - nginx
    networks:
      my-network:
        aliases:
            - bot
networks:
  my-network:
